const ListName = {
  1: "Chandra Mulyagung Sejati",
  2: "Delfia Excelinda",
  3: "DIMAS ROIZ WICAKSANA",
  4: "Galih Hadyan Rajendriya Rahtomo",
  5: "Indra Listyanto",
  6: "Indra Widyadhana Adimatshara",
  7: "Muhamad Surya Triazi Rijar",
  8: "Muhammad Habib Rahman Aqili",
  9: "Muhammad Iqbal Kushadi",
  10: "Muhammad Rafly Baihaqi Lubis",
  11: "Muhammad Raihan Masthofani",
  12: "Pandu Satrio Dighdoyo",
  13: "Rainner Athhar Jati Arifan",
  14: "Rio Jati Hari Bastari",
  15: "Satria Arif Wijayanto",
  16: "Zaki Zufar Risal",
  17: "Agung Arya Putra",
  18: "Albert Juneltino Fanggidae",
  19: "ALIYAH PUTRI APRILIANI",
  20: "Balthazar Christovery Abram Moningka",
  21: "Cheddar Amukti Pranata",
  22: "Fadlan Zainul Ahzan",
  23: "I GEDE SURYA VIDYASTHANA PUTRA",
  24: "KHENAN SAIFUL FEBRISANO",
  25: "Leonardus Rio Ivanosta Pradipta",
  26: "Lucky andrian",
  27: "Muhammad Derril Fredella Irwansa",
  28: "nanda iftikhar suryanegara",
  29: "NAROTAMA WIDYA MANGGALA",
  30: "Pramesvara Rahan Pasha",
  31: "Sebastianus Prayoga Bimantoro",
};

export default ListName;
